---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fl-cp--free-uzp0egas2-0-0-2-hr
  namespace: default
spec:
  chart:
    spec:
      chart: ./fl-cp--free-uzp0egas2-0-0-2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: fl-cp--free-uzp0egas2-0-0-2-source
  interval: 5m0s
  releaseName: fl-cp--free-uzp0egas2-0-0-2
  values:
    global:
      nrf:
        service:
          name: nrf-nnrf
          nodePort: "30800"
          port: "8000"
          type: ClusterIP
      projectName: free5gc
      sbi:
        scheme: http
    initcontainers:
      busybox:
        image: busybox
        tag: 1.32.0
      curl:
        image: initcurl
        registry: towards5gs
        tag: 1.0.0
    mongodb:
      service:
        name: mongodb
        nodePort: "30017"
        port: 27017
        type: ClusterIP
    udm:
      affinity: {}
      autoscaling:
        enabled: false
        maxReplicas: 100
        minReplicas: 1
        targetCPUUtilizationPercentage: 80
      configmap:
        name: udm-configmap
      configuration:
        configuration: |-
          serviceNameList:
            - nudm-sdm
            - nudm-uecm
            - nudm-ueau
            - nudm-ee
            - nudm-pp

          # test data set from TS33501-f60 Annex C.4
          SuciProfile:
            - ProtectionScheme: 1 # Protect Scheme: Profile A
              PrivateKey: c53c22208b61860b06c62e5406a7b330c2b577aa5558981510d128247d38bd1d
              PublicKey: 5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650
            - ProtectionScheme: 2 # Protect Scheme: Profile B
              PrivateKey: F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA
              PublicKey: 0472DA71976234CE833A6907425867B82E074D44EF907DFB4B3E21C1C2256EBCD15A7DED52FCBB097A4ED250E036C7B9C8C7004C4EEDC4F068CD7BF8D3F900E3B4
        logger:
          OpenApi:
            ReportCaller: false
            debugLevel: info
          PathUtil:
            ReportCaller: false
            debugLevel: info
          UDM:
            ReportCaller: false
            debugLevel: info
      image:
        name: towards5gs/free5gc-udm
        pullPolicy: IfNotPresent
      imagePullSecrets: []
      ingress:
        annotations: {}
        enabled: false
        hosts:
        - host: chart-example.local
          paths: []
        tls: []
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 120
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      name: udm
      nodeSelector: {}
      podAnnotations: {}
      podSecurityContext: {}
      readinessProbe:
        failureThreshold: 40
        initialDelaySeconds: 0
        periodSeconds: 1
        successThreshold: 1
        timeoutSeconds: 1
      replicaCount: 1
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      securityContext: {}
      service:
        name: udm-nudm
        port: 80
        type: ClusterIP
      tolerations: []
      volume:
        mount: /free5gc/config/
        name: udm-volume

