---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fl-up--free-g7s2teqfv-0-0-0-hr
  namespace: default
spec:
  chart:
    spec:
      chart: ./fl-up--free-g7s2teqfv-0-0-0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: fl-up--free-g7s2teqfv-0-0-0-source
  interval: 5m0s
  releaseName: fl-up--free-g7s2teqfv-0-0-0
  values:
    global:
      n3network:
        cidr: 29
        excludeIP: 10.100.50.238
        gatewayIP: 10.100.50.238
        masterIf: net0
        name: n3network
        subnetIP: 10.100.50.232
      n4network:
        cidr: 29
        excludeIP: 10.100.50.246
        gatewayIP: 10.100.50.246
        masterIf: net0
        name: n4network
        subnetIP: 10.100.50.240
      n6network:
        cidr: 24
        excludeIP: 10.100.100.254
        gatewayIP: 10.100.100.1
        masterIf: net1
        name: n6network
        subnetIP: 10.100.100.0
      n9network:
        cidr: 29
        excludeIP: 10.100.50.230
        gatewayIP: 10.100.50.230
        masterIf: eth0
        name: n9network
        subnetIP: 10.100.50.224
      projectName: free5gc
      uesubnet: 10.1.0.0/16
      userPlaneArchitecture: single
    upf:
      affinity: {}
      autoscaling:
        enabled: false
        maxReplicas: 100
        minReplicas: 1
        targetCPUUtilizationPercentage: 80
      configmap:
        name: upf-configmap
      configuration:
        configuration:
          ReportCaller: false
          debugLevel: info
          dnn_list:
          - cidr: 10.1.0.0/17
            dnn: internet
            natifname: n6
      image:
        name: towards5gs/free5gc-upf
        pullPolicy: IfNotPresent
      imagePullSecrets: []
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 120
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      n3if:
        ipAddress: 10.100.50.233
      n4if:
        ipAddress: 10.100.50.241
      n6if:
        ipAddress: 10.100.100.12
      name: upf
      nodeSelector: {}
      podAnnotations: {}
      podSecurityContext: {}
      readinessProbe:
        failureThreshold: 40
        initialDelaySeconds: 0
        periodSeconds: 1
        successThreshold: 1
        timeoutSeconds: 1
      replicaCount: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
      securityContext:
        capabilities:
          add:
          - NET_ADMIN
      tolerations: []
      volume:
        mount: /free5gc/config/
        name: upf-volume
    upf1:
      affinity: {}
      autoscaling:
        enabled: false
        maxReplicas: 100
        minReplicas: 1
        targetCPUUtilizationPercentage: 80
      configmap:
        name: upf1-configmap
      configuration:
        configuration:
          ReportCaller: false
          debugLevel: info
          dnn_list:
          - cidr: 10.1.0.0/17
            dnn: internet
            natifname: n6
      image:
        name: towards5gs/free5gc-upf
        pullPolicy: IfNotPresent
      imagePullSecrets: []
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 120
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      n4if:
        ipAddress: 10.100.50.242
      n6if:
        ipAddress: 10.100.100.13
      n9if:
        ipAddress: 10.100.50.226
      name: upf1
      nodeSelector: {}
      podAnnotations: {}
      podSecurityContext: {}
      readinessProbe:
        failureThreshold: 40
        initialDelaySeconds: 0
        periodSeconds: 1
        successThreshold: 1
        timeoutSeconds: 1
      replicaCount: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
      securityContext:
        capabilities:
          add:
          - NET_ADMIN
      tolerations: []
      volume:
        mount: /free5gc/config/
        name: upf1-volume
    upf2:
      affinity: {}
      autoscaling:
        enabled: false
        maxReplicas: 100
        minReplicas: 1
        targetCPUUtilizationPercentage: 80
      configmap:
        name: upf2-configmap
      configuration:
        configuration:
          ReportCaller: false
          debugLevel: info
          dnn_list:
          - cidr: 10.1.0.0/17
            dnn: internet
            natifname: n6
      image:
        name: towards5gs/free5gc-upf
        pullPolicy: IfNotPresent
      imagePullSecrets: []
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 120
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      n4if:
        ipAddress: 10.100.50.243
      n6if:
        ipAddress: 10.100.100.14
      n9if:
        ipAddress: 10.100.50.227
      name: upf2
      nodeSelector: {}
      podAnnotations: {}
      podSecurityContext: {}
      readinessProbe:
        failureThreshold: 40
        initialDelaySeconds: 0
        periodSeconds: 1
        successThreshold: 1
        timeoutSeconds: 1
      replicaCount: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
      securityContext:
        capabilities:
          add:
          - NET_ADMIN
      tolerations: []
      volume:
        mount: /free5gc/config/
        name: upf2-volume
    upfb:
      affinity: {}
      autoscaling:
        enabled: false
        maxReplicas: 100
        minReplicas: 1
        targetCPUUtilizationPercentage: 80
      configmap:
        name: upfb-configmap
      configuration:
        configuration:
          ReportCaller: false
          debugLevel: info
          dnn_list:
          - cidr: 10.1.0.0/17
            dnn: internet
      image:
        name: towards5gs/free5gc-upf
        pullPolicy: IfNotPresent
      imagePullSecrets: []
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 120
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      n3if:
        ipAddress: 10.100.50.233
      n4if:
        ipAddress: 10.100.50.241
      n6if:
        ipAddress: 10.100.100.12
      n9if:
        ipAddress: 10.100.50.225
      name: upfb
      nodeSelector: {}
      podAnnotations: {}
      podSecurityContext: {}
      readinessProbe:
        failureThreshold: 40
        initialDelaySeconds: 0
        periodSeconds: 1
        successThreshold: 1
        timeoutSeconds: 1
      replicaCount: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
      securityContext:
        capabilities:
          add:
          - NET_ADMIN
      tolerations: []
      volume:
        mount: /free5gc/config/
        name: upfb-volume

