---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pingponghr
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./release01/
      sourceRef:
        kind: GitRepository
        name: pingpong
  interval: 5m0s
  releaseName: ping-pong

