---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-fxi9301l-hr
  namespace: default
spec:
  chart:
    spec:
      chart: ./release-fxi9301l
      sourceRef:
        kind: GitRepository
        name: release-fxi9301l-source
  interval: 5m0s
  releaseName: release-fxi9301l
  values:
    global:
      namespace: default
      nsId: a526fab2-f2f4-43de-b081-c6357cef41fc
    internalVldInterface: net1
    ping:
      image:
        imagePullSecrets: []
        pullPolicy: IfNotPresent
        repository: artifactory.riftio.com/docker/rw.ping
        tag: "2004"
      metrics:
        annotations:
          path: /api/v1/ping/metrics
          port: 18888
          scrape: true
        enabled: true
      replicaCount: 1
      serviceType: NodePort
    pong:
      image:
        imagePullSecrets: []
        pullPolicy: IfNotPresent
        repository: artifactory.riftio.com/docker/rw.pong
        tag: "2005"
      metrics:
        annotations:
          path: /api/v1/pong/metrics
          port: 18889
          scrape: true
        enabled: true
      replicaCount: 1
      serviceType: LoadBalancer

